apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:latest
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
      volumes:
      - name: caddyfile
        configMap:
          name: vault-caddyfile
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  annotations:
    metallb.universe.tf/allow-shared-ip: caddy
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.86.102
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https

