# Traefik Helm values
image:
  tag: v3.3.2

# Enable Traefik dashboard
dashboard:
  enabled: true
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.86.102

# Service configuration
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.86.102

# Enable metrics
metrics:
  prometheus:
    enabled: true

# Global configuration
globalArguments:
  - "--global.checkNewVersion=false"
  - "--global.sendAnonymousUsage=false"

# Additional arguments
additionalArguments:
  - "--api.dashboard=true"
  - "--api.debug=true"
  - "--log.level=INFO"
