apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
spec:
  type: {{ .Values.indexer.service.type }}
  ports:
    - port: {{ .Values.indexer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9300
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
