apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexer
spec:
  replicas: {{ .Values.indexer.replicaCount }}
  selector:
    matchLabels:
      {{- include "wazuh.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: indexer
  template:
    metadata:
      labels:
        {{- include "wazuh.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: indexer
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "wazuh.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: wazuh-indexer
          securityContext:
            {{- toYaml .Values.indexer.securityContext | nindent 12 }}
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
          {{- if .Values.indexer.command }}
          command:
            {{- toYaml .Values.indexer.command | nindent 12 }}
          {{- end }}
          {{- if .Values.indexer.args }}
          args:
            {{- toYaml .Values.indexer.args | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.indexer.env | nindent 12 }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}
          volumeMounts:
            - name: wazuh-indexer-data
              mountPath: /usr/share/opensearch/data
            - name: wazuh-indexer-config
              mountPath: /usr/share/opensearch/config
            - name: wazuh-indexer-logs
              mountPath: /usr/share/opensearch/logs
      volumes:
        - name: wazuh-indexer-data
          emptyDir: {}
        - name: wazuh-indexer-config
          emptyDir: {}
        - name: wazuh-indexer-logs
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
