# Default values for wazuh
# This is a YAML-formatted file.

namespace: security

replicaCount: 1

image:
  repository: wazuh/wazuh-manager
  pullPolicy: IfNotPresent
  tag: "4.12.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - wazuh
        topologyKey: kubernetes.io/hostname

podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Wazuh Manager configuration
manager:
  replicaCount: 1
  image:
    repository: wazuh/wazuh-manager
    pullPolicy: IfNotPresent
    tag: "4.12.0"
  service:
    type: ClusterIP
    port: 55000
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  env:
    - name: WAZUH_MANAGER
      value: "wazuh-manager"
    - name: WAZUH_MANAGER_PORT
      value: "55000"

# Wazuh Dashboard configuration
dashboard:
  replicaCount: 1
  image:
    repository: wazuh/wazuh-dashboard
    pullPolicy: IfNotPresent
    tag: "4.12.0"
  service:
    type: LoadBalancer
    port: 443
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  env:
    - name: WAZUH_MANAGER
      value: "wazuh-manager"
    - name: WAZUH_MANAGER_PORT
      value: "55000"
  config:
    username: "admin"
    password: "admin"

# Note: Wazuh agents are typically installed directly on host systems
# For Kubernetes, consider using host-based agents or alternative monitoring solutions

# Ingress configuration
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: wazuh.cooklabs.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wazuh-tls
      hosts:
        - wazuh.cooklabs.net
