# Default values for wazuh
# This is a YAML-formatted file.

namespace: security

replicaCount: 1

image:
  repository: wazuh/wazuh-manager
  pullPolicy: IfNotPresent
  tag: "4.12.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - wazuh
        topologyKey: kubernetes.io/hostname

podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Wazuh Manager configuration
manager:
  replicaCount: 1
  image:
    repository: wazuh/wazuh-manager
    pullPolicy: IfNotPresent
    tag: "4.12.0"
  service:
    type: ClusterIP
    port: 55000
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  env:
    - name: WAZUH_MANAGER
      value: "wazuh-manager"
    - name: WAZUH_MANAGER_PORT
      value: "55000"

# Wazuh Dashboard configuration
dashboard:
  replicaCount: 1
  image:
    repository: wazuh/wazuh-dashboard
    pullPolicy: IfNotPresent
    tag: "4.12.0"
  service:
    type: LoadBalancer
    port: 443
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  env:
    - name: WAZUH_MANAGER
      value: "wazuh-manager"
    - name: WAZUH_MANAGER_PORT
      value: "55000"
  config:
    username: "admin"
    password: "admin"

# Wazuh Agent configuration (DaemonSet)
agent:
  image:
    repository: wazuh/wazuh-agent
    pullPolicy: IfNotPresent
    tag: "4.12.0"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    privileged: true
    capabilities:
      add:
      - SYS_PTRACE
      - AUDIT_CONTROL
      - AUDIT_READ
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - MAC_ADMIN
      - MAC_OVERRIDE
      - MKNOD
      - NET_ADMIN
      - NET_RAW
      - SYSLOG
      - WAKE_ALARM
      - BLOCK_SUSPEND
      - LEASE
      - SYS_BOOT
      - SYS_RAWIO
      - SYSLOG
      - WAKE_ALARM
      - BLOCK_SUSPEND
      - LEASE
      - SYS_BOOT
      - SYS_RAWIO
  env:
    - name: WAZUH_MANAGER
      value: "wazuh-manager"
    - name: WAZUH_MANAGER_PORT
      value: "1514"
    - name: WAZUH_PROTOCOL
      value: "tcp"
    - name: WAZUH_REGISTRATION_SERVER
      value: "wazuh-manager"
    - name: WAZUH_REGISTRATION_PORT
      value: "1515"
    - name: WAZUH_REGISTRATION_PROTOCOL
      value: "tcp"
    - name: WAZUH_KEEP_ALIVE_INTERVAL
      value: "60"
    - name: WAZUH_TIME_RECONNECT
      value: "60"
    - name: WAZUH_REGISTRATION_CA
      value: "/var/ossec/etc/rootca.pem"
    - name: WAZUH_REGISTRATION_CERTIFICATE
      value: "/var/ossec/etc/sslagent.pem"
    - name: WAZUH_REGISTRATION_KEY
      value: "/var/ossec/etc/sslagent.key"
    - name: WAZUH_AGENT_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: WAZUH_AGENT_GROUP
      value: "default"

# Ingress configuration
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: wazuh.cooklabs.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wazuh-tls
      hosts:
        - wazuh.cooklabs.net
