apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-shared-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-hostpath
  hostPath:
    path: /opt/mealie-shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-shared-data
  namespace: mealie
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: shared-hostpath
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared-hostpath
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
