apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v1.4.0
          ports:
            - containerPort: 9000
          env:
            - name: ALLOW_SIGNUP
              value: "true"
            - name: DB_TYPE
              value: "sqlite"
            - name: TZ
              value: "America/Chicago"  # Change to your timezone
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          emptyDir: {}

