# Default values for mealie
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: ghcr.io/mealie-recipes/mealie
  pullPolicy: IfNotPresent
  tag: "v1.4.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 9000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: mealie.cooklabs.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mealie-tls
      hosts:
        - mealie.cooklabs.net

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - mealie
      topologyKey: kubernetes.io/hostname

podDisruptionBudget:
  enabled: true
  minAvailable: 1

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi

# Mealie specific configuration
mealie:
  # Environment variables
  env:
    # Database URL (SQLite for single instance)
    DATABASE_URL: "sqlite:///app/data/mealie.db"
    
    # Default user settings
    DEFAULT_USER: "admin"
    DEFAULT_PASSWORD: "changeme"
    
    # Security settings
    SECRET_KEY: "CHANGE_ME_GENERATE_SECRET_KEY"
    
    # Web settings
    WEB_CONCURRENCY: "1"
    WORKERS_PER_CORE: "1"
    
    # Logging
    LOG_LEVEL: "INFO"
    
    # Features
    ENABLE_SIGNUP: "true"
    ENABLE_OPENAPI: "true"
    
    # Timezone
    TZ: "UTC"
  
  # Health check settings
  healthCheck:
    enabled: true
    path: "/api/health"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  # Liveness probe settings
  livenessProbe:
    enabled: true
    path: "/api/health"
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
