apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-usb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 29Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/usb"

