apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true

