apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 {
          max_concurrent 1000
          health_check 5s
          policy round_robin
          except cooklabs.net
        }
        cache 30
        loop
        reload
        loadbalance
    }
  NodeHosts: |
    192.168.86.27 pi
    192.168.86.31 worker-node-1
    192.168.86.238 worker-node-2
    2603:80a0:3000:2c3:45d4:2fb2:52e4:24f0 pi
    2603:80a0:3000:2c3:51a9:ae92:5448:974b worker-node-1
    2603:80a0:3000:2c3:e549:a726:c9c6:6a2c worker-node-2
