apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.51.6
    helm:
      values: |
        # ArgoCD server configuration
        server:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - host: argocd.cooklabs.net
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.cooklabs.net
          insecure: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi

        # Configuration - DISABLE creation of ConfigMaps (we manage them via GitOps)
        configs:
          params:
            create: false  # Don't create argocd-cmd-params-cm
          cm:
            create: false  # Don't create argocd-cm
          rbac:
            create: false  # Don't create argocd-rbac-cm
          ssh:
            create: false  # Don't create argocd-ssh-known-hosts-cm
          tls:
            create: false  # Don't create argocd-tls-certs-cm

        # Resource configuration
        global:
          image:
            repository: quay.io/argoproj/argocd
            tag: "v3.0.12"

        # Component configuration
        dex:
          enabled: true
        notifications:
          enabled: true
        applicationSet:
          enabled: true

        # Redis persistence
        redis:
          enabled: true
          persistence:
            enabled: true
            size: 1Gi
            storageClass: "local-path"

        # Controller Resource limits
        controller:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Prune=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

