apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.6
    helm:
      values: |
        # ArgoCD server configuration
        server:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-dns
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - argocd.cooklabs.net
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.cooklabs.net
          insecure: true
        
        # Configuration
        configs:
          params:
            server.insecure: "true"
          cm:
            url: https://argocd.cooklabs.net
            server.insecure: "true"
          repositories:
            homelab:
              type: git
              url: https://github.com/cooksey14/homelab.git
              name: homelab
        
        # Resource configuration
        global:
          image:
            repository: quay.io/argoproj/argocd
            tag: "v3.0.12"
        
        # Component configuration
        dex:
          enabled: true
          config: |
            connectors:
              - type: saml
                id: beyondidentity
                name: Beyond Identity
                config:
                  ssoURL: https://auth-us.beyondidentity.com/v1/tenants/000172ee21f04152/realms/3dd6138b020251ad/applications/6aeb17f7-1694-45a8-93e0-85feae3b6644/saml/idp/initiate
                  caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdERENDQS9TZ0F3SUJBZ0lVVWxuR2ZpK0dSK0dBb3M3cTZ1MXpxZTN4S1p3d0RRWUpLb1pJaHZjTkFRRUxCUUF3Z2I4eEN6QUpCZ05WQkFZVEFsVlRNUkV3RHdZRFZRUUlEQWhPWlhjZ1dXOXlhekVSTUE4R0ExVUVCd3dJVG1WM0lGbHZjbXN4R0RBV0JnTlZCQW9NRDBKbGVXOXVaQ0JKWkdWdWRHbDBlVEU2TURnR0ExVUVBd3d4WVhCd2JHbGpZWFJwYjI1ekx6WmhaV0l4TjJZM0xURTJPVFF0TkRWaE9DMDVNMlV3TFRnMVptVmhaVE5pTmpZME5ERTBNRElHQ1NxR1NJYjNEUUVKQVJZbFlYZHpMbWx1Wm5KaGMzUnlkV04wZFhKbFFHSmxlVzl1Wkdsa1pXNTBhWFI1TG1OdmJUQWVGdzB5TlRFeE1EY3lNVEF5TVRCYUZ3MHpOVEV4TURVeU1UQXlNVEJhTUlHL01Rc3dDUVlEVlFRR0V3SlZVekVSTUE4R0ExVUVDQXdJVG1WM0lGbHZjbXN4RVRBUEJnTlZCQWNNQ0U1bGR5QlpiM0pyTVJnd0ZnWURWUVFLREE5Q1pYbHZibVFnU1dSbGJuUnBkSGt4T2pBNEJnTlZCQU1NTVdGd2NHeHBZMkYwYVc5dWN5ODJZV1ZpTVRkbU55MHhOamswTFRRMVlUZ3RPVE5sTUMwNE5XWmxZV1V6WWpZMk5EUXhOREF5QmdrcWhraUc5dzBCQ1FFV0pXRjNjeTVwYm1aeVlYTjBjblZqZEhWeVpVQmlaWGx2Ym1ScFpHVnVkR2wwZVM1amIyMHdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFEQk56L0ZjeTJaS0ZFUEV4Qm5pQUhNUlh0SFZyOW9KWEUxdmZmbmxqNVdpcmVVSWIxVklzVXgyVGo5YitNbGMzVWt1VnFHT21SdDdhTy96SGlCcDlZWmRlQTZkM2pBQ1pNQXVRVTh1WjNybXpKRG41WDNocVF4elM2ZG9JZFhMbUtlcisraDFleE5IVElNK0VDRDlwN1I1WHYvWHVlZ3Z4NHBIM3k5Q2xrcG5nRFltNmowWlJQUkxuODJPYXRIaGZBWmVWZFUrTHpaSEJkUXpVVGtnR0lpaDE5TTVyZVp6TElqOThDOWlSNGtnZ21YNHVXenJTRzBmeldBT3FGNG1Ha2ZFSmhVd2dxYXRrVkdBajUzcGR5WVlJakNadnFqZHViNFJ4MXU5ZG4rcDRoZ244UUFkVW5BdE83emYwejJNVEFIMlRIcXVnekRvSnVQRXB5QkxqcHQ0aEhNWnBLSnBWZXVmdjMrU0dTby9QbC90Rlp6YTF4TUI0cG1WRGNTS2p2Y1Z0VHlNelhoR2FNdGJRQ29XN0tSRGpFUWVHRSs5a3FqdTh1c2ZuYXdWWm1vckFnYmsxMVdkdUJwNW1kL3g1UHBlOEthb0tQWlFvK1VKNzhQUlk2aE1hTXZBV0FIMVVGNVRWOHpFaXU2d240RnRDWDhlVHQrZkdxWmo1ZjAxVEVmTndNQU8yblFQenN1R1V4OWV1MVpSc1ZCZndLcm9aaVk0WFEyVWhCZnBWSTlvVDZhbTh0T2xCNWhaais0dmh1MXluTDlZTS8ycm55SEZqbTYyalBUS2NLWU1BYTg0VFVHVnlzZTUxOFZzQWhWc1MxL210Z0VaZlhHeFlRNHoreW44Q1h3RkwyTVAyZCtWMVpld00za3c5WFhuR2dwd1dtS0ttWDloR2ppWndJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJuZ0d1Um1lc043WlpkMitqK1VPWGpnWDJ5dlBBQmN5eDlEekNpU3RqeU1vSzVCdlVlZmo4UkhCMWRqZXlMYlBrR09pUFp4b0RITVJCTlp4QnBFUUc1Z2dISUpHRjhzL2lIL3NRRzAzc0c5M2o0VStWR2hzUXFlUTZZMDVnMDYvODBiYlpDdE9ueFJpcnduZm1UTnFtcnVhT1BiSm5KR1l2S0RMa1NVNjVhaVBFeGt3WlFlMURvSDAwMVJaVHc3QWIwNCtuU0hHckZzVGhYczJCcTNlMDhGU1RrRnpFN1RNVnNaY0U2VUlHT1BkNVl0UG8xL2RjbTB6K2czU2x4ZDVmcTZydFRBT2ZiU0tPVkw0STVTVWJRb0lTcVlVNUI0NmJwWXRKT2FvUHpNVHEzSlVWVTZzQlMyMExWVGF1NFE3aEg2Vjc2S0FoUzUraUZtQy9qbW5ZYnJad2JsNGgzR0pwWklPT3VsOWJSOUhEdWVYb21lTmx2UUxMVGZWODhNRjdabVNuVUQ1NUw1QVcxMy92cXZkdnJ1UkZWTjFrQkFmd3Y0OENWZldzSjRUSytnWWp6Z3BGNE8va2RFbUpJdGsybTM5WitITzlZQVppcUdXYzhicTBjaS9pT1kvSlhKSi92ek9BYTczZFl6NmpUQXdOYSs1RFlPRjFaWTJXQ0dYSllRdFM2TUQ0bmV3N0NSSm5pUE5DVlk3RFpVMGY3c2VnUHBFNjFPdmlWdEI0Q2pqQ2FwbzBxcHkya0hMR291SVZEUlVSVmhuSHgyaWN1a1hNWGRIUmdTUmdpVndITmFTWTFPcWtCUXNNeVYweUVBRDV2aUpBTWwxYjQ1MWtlNnNKUXg0R2JacHJNL3h6eGtxb3FKTis1Sm1SOUdCVzVwLzNUeXk0cnJhbHoydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                  redirectURI: https://argocd.cooklabs.net/api/dex/callback
                  usernameAttr: name
                  emailAttr: email
                  groupsAttr: groups
        notifications:
          enabled: true
        applicationSet:
          enabled: true
        
        # Redis persistence
        redis:
          enabled: true
          persistence:
            enabled: true
            size: 1Gi
            storageClass: "local-path"
        
        # Resource limits
        server:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
        controller:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true