apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.12.0
    helm:
      values: |
        # Cert-Manager configuration
        global:
          leaderElection:
            namespace: cert-manager
        
        # Install CRDs
        installCRDs: true
        
        # Resource configuration
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        # Webhook configuration
        webhook:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # CA Injector configuration
        cainjector:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # Node selector and affinity
        nodeSelector: {}
        affinity: {}
        tolerations: []
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
        
        # Service account
        serviceAccount:
          create: true
          name: cert-manager
        
        # Prometheus monitoring
        prometheus:
          enabled: false  # Enable if you want Prometheus metrics
        
        # Startup probe
        startupapicheck:
          enabled: true
          timeout: 1m
          backoffLimit: 30
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
