apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.15.2
    helm:
      values: |
        # MetalLB configuration
        controller:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
        
        speaker:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
        
        # Node selector and affinity
        nodeSelector: {}
        affinity: {}
        tolerations: []
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
        
        # Service account
        serviceAccount:
          create: true
          name: metallb
        
        # Prometheus monitoring
        prometheus:
          enabled: false  # Enable if you want Prometheus metrics
        
        # Webhook configuration
        webhook:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
        
        # Additional configuration files
        configInline:
          # IP Address Pool
          - apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: default
              namespace: metallb-system
            spec:
              addresses:
              - 192.168.86.100-192.168.86.110
              autoAssign: true
              avoidBuggyIPs: true
              serviceAllocation:
                priority: 100
                serviceSelector:
                  matchLabels:
                    app.kubernetes.io/name: traefik
          
          # L2 Advertisement
          - apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: default
              namespace: metallb-system
            spec:
              ipAddressPools:
              - default
              interfaces:
              - wlan0
              nodeSelectors:
              - matchLabels:
                  kubernetes.io/hostname: pi
              - matchLabels:
                  kubernetes.io/hostname: worker-node-1
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
