apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cooksey14/homelab.git
    path: monitoring
    targetRevision: HEAD
    helm:
      values: |
        # Grafana configuration
        grafana:
          enabled: true
          ingress:
            enabled: true
            className: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - host: grafana.cooklabs.net
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.cooklabs.net
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

        # Prometheus configuration
        prometheus:
          enabled: true
          ingress:
            enabled: true
            className: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - host: prometheus.cooklabs.net
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.cooklabs.net
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

        # Postgres configuration
        postgres:
          enabled: true
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            POSTGRES_DB: "monitoring"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "changeme"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Prune=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
