apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cooksey14/homelab.git
    path: vaultwarden
    targetRevision: HEAD
    helm:
      values: |
        # Override default values for production
        vaultwarden:
          env:
            # Generate a secure admin token
            ADMIN_TOKEN: "s2duRmIOYy/vi9qnFE0Wi7Ac2t4PlrWlTqLnrCqKOWsmOQdEED3iu7CWEXh+vISH"
            # Set your domain
            DOMAIN: "https://vaultwarden.cooklabs.net"
            # Disable signups in production (enable for initial setup)
            SIGNUPS_ALLOWED: "true"
            # Enable invitations
            INVITATIONS_ALLOWED: "true"
            # Disable password hints for security
            SHOW_PASSWORD_HINT: "false"
            # Increase password iterations for better security
            PASSWORD_ITERATIONS: "100000"
            # Enable WebSocket support
            WEBSOCKET_ENABLED: "true"
            # Set log level
            LOG_LEVEL: "warn"
            # Enable extended logging
            EXTENDED_LOGGING: "true"
            # Icon cache settings
            ICON_CACHE_TTL: "2592000"
            ICON_CACHE_NEGTTL: "2592000"
        
        # Resource limits
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # Persistence settings
        persistence:
          enabled: true
          storageClass: "vaultwarden-shared-hostpath"
          accessMode: ReadWriteMany
          size: 2Gi
          sharedStorage:
            enabled: true
            hostPath: "/opt/vaultwarden-shared"
            reclaimPolicy: "Retain"
        
        # Ingress settings
        ingress:
          enabled: true
          className: "traefik-helm"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
            traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: vaultwarden.cooklabs.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: vaultwarden-tls
              hosts:
                - vaultwarden.cooklabs.net
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Prune=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
