apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cooksey14/homelab.git
    path: wazuh
    targetRevision: HEAD
    helm:
      values: |
        # Override default values for production
        namespace: security
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    helm:
      values: |
        # Override default values for production
        namespace: security
        
        # Manager configuration
        manager:
          replicaCount: 1
          image:
            repository: kalingth/wazuh-manager
            pullPolicy: IfNotPresent
            tag: "4.8.2"
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: true
        
        # Indexer configuration
        indexer:
          replicaCount: 1
          image:
            repository: kalingth/wazuh-indexer
            pullPolicy: IfNotPresent
            tag: "4.8.2"
          service:
            type: ClusterIP
            port: 9200
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          securityContext:
            runAsUser: 9255
            runAsGroup: 9255
            runAsNonRoot: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - ALL
              drop: []
          command: ["/bin/bash"]
          args: ["-c", "echo 'Starting OpenSearch directly...' && /usr/share/wazuh-indexer/bin/opensearch"]
          env:
            - name: "OPENSEARCH_JAVA_OPTS"
              value: "-Xms1g -Xmx1g"
            - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
              value: "admin"
        
        # Dashboard configuration
        dashboard:
          replicaCount: 1
          image:
            repository: kalingth/wazuh-dashboard
            pullPolicy: IfNotPresent
            tag: "4.8.2"
          command: ["/usr/share/wazuh-dashboard/bin/opensearch-dashboards"]
          args: ["--host", "0.0.0.0", "--port", "5601", "--allow-root"]
          service:
            type: LoadBalancer
            port: 5601
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: true
          env:
            - name: WAZUH_MANAGER
              value: "wazuh-manager"
            - name: WAZUH_MANAGER_PORT
              value: "55000"
            - name: OPENSEARCH_DASHBOARDS_ALLOW_ROOT
              value: "true"
            - name: OPENSEARCH_HOSTS
              value: "https://wazuh-indexer:9200"
          config:
            username: "admin"
            password: "admin"
        
        # Agent configuration (DaemonSet for each node) - Using community ARM64 image
        agent:
          image:
            repository: kalingth/wazuh-agent
            pullPolicy: IfNotPresent
            tag: "4.8.2"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            privileged: true
        
        # Ingress settings
        ingress:
          enabled: true
          className: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
            traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: wazuh.cooklabs.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: wazuh-tls
              hosts:
                - wazuh.cooklabs.net
        
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        
        # Security context
        podSecurityContext:
          fsGroup: 1000
        
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        
        # Anti-affinity for high availability
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - wazuh
                topologyKey: kubernetes.io/hostname
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
