{{- if and .Values.prometheus.enabled .Values.prometheus.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "monitoring.prometheus.fullname" . }}-pvc
  labels:
    {{- include "monitoring.prometheus.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.prometheus.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
  {{- if .Values.prometheus.persistence.storageClass }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass }}
  {{- end }}
{{- end }}
