{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring.prometheus.serviceAccountName" . }}
  labels:
    {{- include "monitoring.prometheus.labels" . | nindent 4 }}
  {{- with .Values.prometheus.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
