apiVersion: v2
name: homelab-command-center
description: Modern HomeLab monitoring and management platform
type: application
version: 0.2.10
appVersion: "1.0.0"
keywords:
  - homelab
  - monitoring
  - kubernetes
  - dashboard
home: https://github.com/cooksey14/homelab
sources:
  - https://github.com/cooksey14/homelab
maintainers:
  - name: Colin Cooksey
    email: your-email@example.com
