version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: homelab_command_center
      POSTGRES_USER: homelab
      POSTGRES_PASSWORD: homelab
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homelab -d homelab_command_center"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://homelab:homelab@postgres:5432/homelab_command_center
      - REDIS_URL=redis://redis:6379/0
      - KUBE_CONFIG_PATH=/var/run/secrets/kubernetes.io/serviceaccount/token
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker if needed
    restart: unless-stopped

  celery-worker:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: uv run celery -A app.workers.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://homelab:homelab@postgres:5432/homelab_command_center
      - REDIS_URL=redis://redis:6379/0
      - KUBE_CONFIG_PATH=/var/run/secrets/kubernetes.io/serviceaccount/token
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  celery-beat:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: uv run celery -A app.workers.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://homelab:homelab@postgres:5432/homelab_command_center
      - REDIS_URL=redis://redis:6379/0
      - KUBE_CONFIG_PATH=/var/run/secrets/kubernetes.io/serviceaccount/token
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
