apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 192.168.86.100-192.168.86.110
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
  interfaces:
  - wlan0
  # Add more robust configuration
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: pi
  # Increase advertisement interval for stability
  advertisementInterval: 1s
  # Enable graceful shutdown
  gracefulShutdown: true
