{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-data
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}

{{- if .Values.persistence.sharedStorage.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vaultwarden.fullname" . }}-shared-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
  - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.sharedStorage.reclaimPolicy }}
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: {{ .Values.persistence.sharedStorage.hostPath }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.persistence.sharedStorage.reclaimPolicy }}
{{- end }}
