apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
    app.kubernetes.io/name: security
    app.kubernetes.io/instance: security
    app.kubernetes.io/component: security-stack
    app.kubernetes.io/part-of: security-stack
    app.kubernetes.io/managed-by: argocd
