# Nginx Ingress Controller Helm values
controller:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.86.101
  metrics:
    enabled: true
    service:
      type: ClusterIP
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "false"

# Enable metrics
metrics:
  enabled: true
  service:
    type: ClusterIP
