apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9090
    nodePort: 30089
  selector:
    app: prometheus
