# Prometheus Helm values
prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  server:
    nodeSelector:
      kubernetes.io/hostname: pi
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      runAsGroup: 1000
      fsGroup: 1000
    persistentVolume:
      enabled: true
      existingClaim: "prometheus-usb-pvc"
      volumeName: "prometheus-usb-pv"
    service:
      type: NodePort
      nodePort: 30089
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

# Service configuration
service:
  type: NodePort
  nodePort: 30089
  port: 80
  targetPort: 9090
