apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-path

