{{- if false }}
# Namespace is managed by the 'namespaces' ArgoCD application
# Disabled to avoid conflicts
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "homelab-command-center.labels" . | nindent 4 }}
