{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homelab-command-center.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab-command-center.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    {{- range .Values.postgresql.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
