{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-command-center.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab-command-center.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "homelab-command-center.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
